to_do_app/to_do_app/ToDoApp/urls.py
from django.urls import path
from . import views
from .views import Home,TaskDetail,user_login, addTask,TaskUpdate,DeleteView,calendar,register,TaskListView
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static


app_name = 'ToDoApp'

urlpatterns = [
    # path('',views.landingpage,name='landingpage'),
    path('home/',Home.as_view(),name = 'home'),
    path('listview/',TaskListView.as_view(),name = 'listview'),
    # path('register/',register.as_view(),name='register'),
    path('register/',views.register,name='register'),
    path('',user_login.as_view(),name ='login'),
    path('logout/',LogoutView.as_view(next_page='ToDoApp:login'),name ='logout'),
    path('addTask/',addTask.as_view(),name='addTask'),
    path('task-update<int:pk>/', TaskUpdate.as_view(), name='task-update'),
    path('task-delete/<int:pk>/', DeleteView.as_view(), name='task-delete'),
    path('<int:pk>/',TaskDetail.as_view(), name='taskdetail'),
    path('calendar/',calendar.as_view(),name = 'calendar'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

to_do_app/to_do_app/to_do_app/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('ToDoApp.urls')),
]

to_do_app/to_do_app/ToDoApp/models.py
from django.db import models
from django.contrib.auth.models import User

# user models.
class UserProfileInformation(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=10)
    # profile_picture = models.ImageField(upload_to='profile_pictures',blank=True)

    def __str__(self):
        return self.user.first_name,self.user.last_name,self.user.email,self.user.username,self.phone_number
    

# the to do task model.

class Task(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE,null=True,blank=False)
    title = models.CharField(max_length=250)
    activity = models.TextField(max_length=1000)
    starting_time = models.DateTimeField()
    reminder_time =models.DateTimeField()

    status_choice = (('Un attempted','Un attempted'),('Done','Done'))
    status = models.CharField(choices=status_choice, max_length=15,default='un attempted')

    def __str__(self):
        return self.title
    class meta:
        order_with_respect_to ='user'

to_do_app/to_do_app/ToDoApp/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User

# user and  userprofile information forms
class User_Form(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('first_name','last_name','username','email','password')

class UserProfileForm(forms.ModelForm):

    class Meta():
        model = UserProfileInformation
        fields = ('phone_number',)

# task form code

class TaskForm(forms.ModelForm):
    class Meta():
        model = Task
        fields = ('title','activity','starting_time', 'reminder_time','status')

to_do_app/to_do_app/ToDoApp/views.py
from django.shortcuts import render,redirect
from .models import *
from .forms import *
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate, login, logout
from .sendemail import To_Do_email_notification
from datetime import date,datetime
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView,DeleteView,UpdateView,FormView
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
import datetime
from django.views import generic



# Create your views here.
def landingpage(request):
    return render(request,'ToDoApp/landingpage.html',{})

class TaskListView (LoginRequiredMixin,ListView):
    model = Task
    template_name = 'ToDoApp/TaskListView.html'
    context_object_name = 'task_list'
    queryset = Task.objects.order_by('starting_time')

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks_list']= context['task_list'].filter(user = self.request.user)
        return context

class Home(LoginRequiredMixin,ListView):
    model = Task
    template_name = 'ToDoApp/home.html'
    context_object_name = 'task_list'
    queryset = Task.objects.order_by('starting_time')
    
    # sending email if task list is time reminder time has reached 
    tasklist = Task.objects.all()
    if tasklist:
        for task in tasklist:
            task_reminder_time = task.reminder_time.date()
            now_duration = datetime.datetime.now().date()
            duration_diff = task_reminder_time - now_duration

            time_now = datetime.datetime.now().time().replace(second=0,microsecond=0)
            reminder_time = task.reminder_time.time().replace(second=0,microsecond=0)

            print(time_now,reminder_time, duration_diff)
            

            if (duration_diff.days == 0) :
                if (time_now == reminder_time):
                    subject = task.title
                    To_Do_email_notification(task.user.email,f'Hello <b>{task.user.first_name}</b>,<br>This is just a simple notification about your to do activity titled "{task.title}" that is scheduled to start on {task.starting_time}<br>Click here to view task: <a href="https://todo-production-df7e.up.railway.app/{task.pk}/"><b>{task.title}</b></a><br>With regards<br>Calvin<br>To-do-admin',subject)
                else:pass
            else:pass

    # tasklismenu = Task.objects.filter('user_id')
    # queryset = Task.objects.filter('user')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks_list'] = context['task_list'].filter(user = self.request.user).order_by('starting_time')
        context['count'] = context['task_list'].filter(status = 'Un attempted').count()

        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks_list'] = context['tasks_list'].filter(title__contains=search_input)
        context['search_input'] = search_input
      
        return context

# def home(request):
#     task_list = Task.objects.all
#     return render(request,'ToDoApp/home.html',{'task_list':task_list})


class addTask(LoginRequiredMixin,CreateView):
    model = Task
    fields = ('title','activity','starting_time','reminder_time','status')
    template_name = 'ToDoApp/taskform.html'
    success_url = reverse_lazy('ToDoApp:home')

    # def post(self, request):
    #     form = self.form_class(request.POST)
    #     title = request.POST['title']
    #     activity = request.POST['activity']
    #     starting_time = request.POST['starting_time']
    #     reminder_time = request.POST['reminder_time']
    #     status = request.POST['status']

    #     return reverse_lazy('ToDoApp:home')
        
        # return super(addTask, self).render_to_response(context={})
    
    def form_valid(self, form):
        form.instance.user = self.request.user
    
        # querying the date if its not beyond 7 days
        startingtask = form.instance.starting_time.date()
        duration = datetime.datetime.now().date()
        date_diff = startingtask-duration
        
        if (date_diff.days)>(7):
            form.add_error('starting_time','Task should not be set for a period beyond a week')
            return self.form_invalid(form)
        else:
            return super(addTask,self).form_valid(form)
        # return super(addTask,self).form_valid(form)
    
   


# @login_required
# def addTask(request):
#     task_form = TaskForm(request.POST or None)
#     if request.method =='POST':
#         tast_form = TaskForm(data = request.POST)
#         # user = User_Form.objects.filter()
#         if tast_form.is_valid():
#             task_form
#             tast_form.save()
#             return HttpResponseRedirect('home')
#         else:
#             print(User_Form.errors)
#     else:
#         task_form = TaskForm()

#     return render(request,'ToDoApp/taskform.html',{'task_form':task_form})


# class register(FormView):
#     template_name = 'ToDoApp/register.html'
#     form_class = UserCreationForm
#     redirect_authenticated_user = True
#     success_url = reverse_lazy('ToDoApp:home')

#     def form_valid(self, form):
#         user = form.save()
#         if user is not None:
#             login(self.request, user)
#         return super(register, self).form_valid(form)

#     def get(self, *args, **kwargs):
#         if self.request.user.is_authenticated:
#             return redirect('tasks')
#         return super(register, self).get(*args, **kwargs)


def register(request):

    registered = False

    if request.method == "POST":
        user_form = User_Form(data= request.POST)
        user_profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and user_profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            subject = 'Account Creation'
            To_Do_email_notification(user.email,f'Hello <b>{user.first_name}</b><br>You have successfully created an account with us.<br> With regards<br>To Do Team <br>',subject)

            # profile = user_profile_form.save(commit = False)
            # profile.user = user

            # if 'profile_picture' in request.FILES:
            #      profile.profile_picture = request.FILES['profile_picture']

            # profile.save()

            registered = True

        else:
             print(user_form.errors,user_profile_form.errors)
    else:
        user_form = User_Form()
        user_profile_form = UserProfileForm()

    return render(request,'ToDoApp/register.html',{
        'user_form':user_form,
        'user_profile_form':user_profile_form,
        'registered':registered,
    })

class user_login(LoginView):
    template_name = 'ToDoApp/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('ToDoApp:home')

# def user_login(request):

#     if request.method == "POST":
#         username = request.POST.get('username')
#         password = request.POST.get('password')

#         user = authenticate(username = username,password = password)

#         if user:
#             if user.is_active:
#                 login(request,user)
#                 return HttpResponseRedirect(reverse('home'))
#             else:
#                 return HttpResponseRedirect("ACCOUNT NOT ACTIVE")
#         else:
#             print('someone tried loging in ')
#             return HttpResponse('invalid login details supplied')
#     else:
#         return render(request,'ToDoApp/login.html')
    

@login_required
def  user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('landingpage'))

# sending email at the time of reminder of the task
# def reminder_email(request):
#     task = Task.objects.all

# detail vieew

class TaskDetail(LoginRequiredMixin,DetailView):
    model = Task
    template_name = 'ToDoApp/taskdetail.html'
    context_object_name = 'task'


# def taskdetail(request,id):
#     # if request.method == 'GET':
#         taskss = Task.objects.get(id = id)
#         return render(request,'ToDoApp/taskdetail.html',{'taskss':taskss})
class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    fields =('title','activity','starting_time','reminder_time','status')
    template_name = 'ToDoApp/edit.html'
    success_url = reverse_lazy('ToDoApp:home')


class DeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = 'tasks'
    template_name = 'ToDoApp/delete.html'
    success_url = reverse_lazy('ToDoApp:home')

class calendar (LoginRequiredMixin,generic.View):
    model = Task
    template_name = 'ToDoApp/calendar.html'
    context_object_name = 'task_list'
    

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context["tasks_list"]= context['task_list'].filter(user = self.request.user)
        return context
    
    
    
    def get(self, request, *args, **kwargs):
        # forms = self.form_class()
        events = Task.objects.filter    (user=request.user)
        # events_month = Task.objects.get_running_events(user=request.user)
        event_list = []
        # start: '2020-09-16T16:00:00'
        for event in events:
            event_list.append(
                {
                    "title": event.title,
                    "start": event.starting_time.strftime("%Y-%m-%dT%H:%M:%S"),
                    "end": event.reminder_time.strftime("%Y-%m-%dT%H:%M:%S"),

                }
            )
        context = {"events": event_list}

to_do_app/to_do_app/templates/ToDoApp/TaskListView.html
<!DOCTYPE html>
{%extends 'ToDoApp/base.html'%}
{%load static%}

{%block body %}
<div class="table table-success table-striped" width="100%">
    <table>
        <col style="width:10%">
        <col style="width: 30%">
        <col style="width: 10%">
        <col style="width: 10%">
        <tr>
            <th>Title</th>
            <th>Starting Time</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
        {%if tasks_list%}
        {%for task in tasks_list %}
        <tr>
            
            <td><a href="{% url 'ToDoApp:taskdetail'  task.id%}">{{task.title}}</a></td>
            <td>{{task.starting_time.date}}({{task.starting_time.time}})</td> 
            <td>{{task.status}}</td>
            <td>
                <a href="{% url 'ToDoApp:task-update' task.id%}"><button class="btn btn-sm btn-info">Update</button></a>
                <a href="{% url 'ToDoApp:task-delete' task.id%}"><button class="btn btn-sm btn-info">Delete</button></a>
            </td> 
        {%endfor%} 
        {%else%}
            <p>no items</p>
        {%endif%}
    </tbody>
</table>
<br><br>
</div>

<a href="{%url 'ToDoApp:home'%}"><button  class="btn btn-sm btn-info">Back</button></a>
{%endblock%}

to_do_app/to_do_app/templates/ToDoApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title></title>
</head>
<body>
  <style>
    .container2{
      width: 100%;
      height: 100%;
    }
  </style>
  <div class="container2">
    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
      <div class="container-fluid">
        {%if request.user.is_authenticated%}
        <a class="navbar-brand" href="#">{{request.user|title}}</a>
        {%endif%}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{%url 'ToDoApp:home'%}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{%url 'ToDoApp:listview'%}">List View</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{%url 'ToDoApp:addTask'%}">Add Task</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{%url 'ToDoApp:calendar'%}">Calender</a>
            </li>
          </ul>
          <span class="navbar-text">
          {%if request.user.is_authenticated%}
              <a href="{%url 'ToDoApp:logout'%}">logout</a>
          {%else%}
          <a href="{%url 'ToDoApp:login'%}">login</a>
          {%endif%}
          </li> </span>
        </div>
      </div>
    </nav>
  {%block body%}

  {%endblock%}
  </div>   
</body>

</html>

to_do_app/to_do_app/templates/ToDoApp/calendar.html
<!DOCTYPE html>
<html>

<head>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.css" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-primary">
    <div class="container-fluid">
      {%if request.user.is_authenticated%}
      <a class="navbar-brand" href="#">{{request.user|title}}</a>
      {%endif%}
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
        aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%url 'ToDoApp:home'%}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'ToDoApp:listview'%}">List View</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'ToDoApp:addTask'%}">Add Task</a>
          </li>

        </ul>
        <span class="navbar-text">
          {%if request.user.is_authenticated%}
          <a href="{%url 'ToDoApp:logout'%}">logout</a>
          {%else%}
          <a href="{%url 'ToDoApp:login'%}">login</a>
          {%endif%}
          </li> </span>
      </div>
    </div>
  </nav>

  <div class="container">
    <div class="row">
<br>
      {% block content %}
      <div class="col-md-12">
        <div id='calendar'></div>
      </div>
      {% endblock %}
    </div>
  </div>
  <script src='https://cdn.jsdelivr.net/npm/fullcalendar-scheduler@6.1.5/index.global.min.js'></script>
  <script>
   
    document.addEventListener('DOMContentLoaded', function () {
        var calendarEl = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarEl, {
          initialView: 'dayGridMonth',
          headerToolbar:{
            left: 'prev,next today',
           center: 'title',
           right: 'dayGridMonth,timeGridWeek,timeGridDay'
          },
          select: function(arg) {
            console.log('clicked')
            var modal = document.getElementById('eventModal')
            modal.style.display = 'block'
            calendar.unselect()
          },
         events: {{ events|safe }},
//           [
//     {
//       id: 'a',
//       title: 'my event',
//       start: '2023-04-01'
//     }
//   ]
})

// var event = calendar.getEventById('eventModal') // an event object!
// var start = event.start // a property (a Date object)
// console.log(start.toISOString()) 
       
        calendar.render();
      });
      const closeBtn1 = document.getElementById('modalClose1');
      const closeBtn2 = document.getElementById('modalClose2');
      closeBtn1.addEventListener('click',()=>{
        const eventModal = document.getElementById('eventModal')
        eventModal.style.display = 'none';
      });
      closeBtn2.addEventListener('click',()=>{
        const eventModal = document.getElementById('eventModal')
        eventModal.style.display = 'none';
      });

  </script>
</body>

</html>

to_do_app/to_do_app/templates/ToDoApp/delete.html
<form method="post">{% csrf_token %}
     
 
 
 
    <p>Are you sure you want to delete "{{ tasks }}"?</p>
     
     
     
     
        <input type="submit" value="Confirm">
    </form>

to_do_app/to_do_app/templates/ToDoApp/edit.html
<!DOCTYPE html>
{%extends 'ToDoApp/base.html'%}
{%load static%}

{%block body %}
<style>
    .container {
    padding: 2%;
    border: 2px;
    width: 98%;
    height: 90%;
    margin: 0 auto;
    position: relative;
    background-color:  #36d8d8;
    margin-bottom: 10%;
    margin-top: 10%;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
    border-radius: 10px;

  }
</style>
<br>
<div class="container">
    <div class="">
        <form action="{%url 'ToDoApp:addTask'%}" method="POST">
            {%csrf_token%}
            <br>
            {{form.as_p}}
            <!-- <br>
            <label for="title">Title: </label>
            <input type="text" name="title" id="title" ><br><br>
            <label for="activity">Activity: </label>
            <input type="text" name="activity"  id="activity" ><br><br>
            <label for="starting_time"> Starting date and time: </label>
            <input type="datetime-local" name="starting_time" id="starting_time"><br><br>
            <label for="reminder_time">Reminder date and time: </label>
            <input type="datetime-local" name="reminder_time" id="reminder_time"><br><br>
            <label for="status">Status: </label>
            <input type="text" name="status"  id="status"><br><br>
            <button type="submit">Add Task</button><br> -->
        </form><br>
        <a href="{%url 'ToDoApp:home'%}"><button class="btn btn-sm btn-info"> Save </button></a>

        <a href="{%url 'ToDoApp:home'%}"><button class="btn btn-sm btn-info"> Cancel </button></a>
    </div>
</div>
{%endblock%}

to_do_app/to_do_app/templates/ToDoApp/home.html
<!DOCTYPE html>
{%extends 'ToDoApp/base.html'%}
{%load static%}
<link rel="stylesheet" href="{% static 'css/tasklist.css'%}">
    {%block body%}
    <style>

        body{
            background-color: #fff;
        }
    
        .center-column{
            width:80%;
            margin: 20px auto;
            padding:0%;
            background-color:whitesmoke;
            border-radius: 3px;
            /* box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75); */
        }
    
        .item-row{
            width: 100%;
            background-color: #85c9ec;
            margin: 10px;
            padding: 20px;
            border-radius: 3px;
            color: #fff;
            font-size: 16px;
            box-shadow: 0px -1px 10px -4px rgba(0,0,0,0.75);
        }
    
        .btn-danger{
            background-color: #ffae19;
            border-color: #e59400;
        }
        .container1{
            width: 100%;
            height: 100%;
            padding: 0%;
            background-color:whitesmoke;
        }
        /* .link {
        position: fixed;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        z-index: 1;
      } */
      .h3{
        color: #f6f9fa;
      }
      
    
    </style>
    <div class="container1">
        <h4 style="text-align: center;">My Task List</h4>
        <div class="center-column">
            <div id="search-add-wrapper" style="width: 80;padding-left: 10%;padding-bottom: 5%;">
                <form method="GET" style="display: flex;">
                   <input type='text' name='search-area' placeholder="Search your task" value="{{search_input}}">
                   <input class="btn btn-sm btn-info" type="submit" value='Search'>
               </form>
           </div>
            {%if tasks_list%}
                {%for task in tasks_list %}
                <div class="item-row">
                            
                    {% if task.status == Done %}
                    <strike>{{task.title}}</strike>
                    {% else %}
                    <span><h3><a href="{% url 'ToDoApp:taskdetail'  task.id%}">{{task.title}}</a></h3></span>
                    <p><b>Time</b>: {{task.starting_time.date}}({{task.starting_time.time}}) </p>
                    <!-- <a href="{% url 'ToDoApp:taskdetail'  task.id%}">
                        <span class="link"></span>
                      </a> -->
                    {% endif %}
                    <a class="btn btn-sm btn-info" href="{% url 'ToDoApp:task-update' task.id%}">Update</a>
                    <a class="btn btn-sm btn-danger" href="{% url 'ToDoApp:task-delete' task.id%}">Delete</a>
                </div>
                {%endfor%} 
                {%else%}
                    <p>no items</p>
                {%endif%}
            </div>
        <div class="b">
            <center><a href="{%url 'ToDoApp:addTask'%}" ><button class="btn btn-sm btn-info" >Add Task</button></a></center> 
        </div>    
    </div>
        {%endblock%}

to_do_app/to_do_app/templates/ToDoApp/taskform.html
<!DOCTYPE html>
{%extends 'ToDoApp/base.html'%}
{%load static%}

{%block body %}
<style>
    .container1 {
    padding: 2%;
    border: 2px;
    width: 98%;
    height: 90%;
    margin: 0 auto;
    position: relative;
    background-color:  #36d8d8;
    margin-bottom: 10%;
    margin-top: 10%;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
    border-radius: 10px;

  }
</style>
<br>
<div class="container1">
    <div class="">
        <form action="{%url 'ToDoApp:addTask'%}" method="POST">
            {%csrf_token%}
            <br>
            {{form.as_p}}
            <!-- <br>
            <label for="title">Title: </label>
            <input type="text" name="title" id="title" ><br><br>
            <label for="activity">Activity: </label>
            <input type="text" name="activity"  id="activity" ><br><br>
            <label for="starting_time"> Starting date and time: </label>
            <input type="datetime-local" name="starting_time" id="starting_time"><br><br>
            <label for="reminder_time">Reminder date and time: </label>
            <input type="datetime-local" name="reminder_time" id="reminder_time"><br><br>
            <label for="status">Status: </label>
            <!-- <input type="text" name="status"  id="status"><br><br> -->
            <button type="submit" class="btn btn-sm btn-info">Add Task</button>
              </form><br>
              <a href="{%url 'ToDoApp:home'%}"><button class="btn btn-sm btn-info"> Back </button></a>
      
        </div>
</div>
{%endblock%}